# Generated by Django 6.0.2 on 2026-03-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='poblished_at',
            new_name='published_at',
        ),
    ]
