# Generated by Django 6.0.2 on 2026-03-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Release date'),
        ),
    ]
