# Generated by Django 6.0.2 on 2026-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='available_since',
            field=models.DateTimeField(null=True),
        ),
    ]
