# Generated by Django 6.0.2 on 2026-03-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_demomodel_available_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demomodel',
            name='available_since',
        ),
    ]
